### ISSUE TITLE
Stable Release for Laravel 11 Support?

### ISSUE THREAD

**Issue by mechelon** [rajentrivedi/tokenizer-x#25]
### What happened?

Hey there,

first up, thanks for your work on the package!
I was just wondering, do you plan to release the Laravel 11 support as a stable version as well? Currently, it's only available via `dev-upgrade-laravel-11`, but not in the 1.0.2 version - it states that in the title, but the dependencies are missing from the `composer.json` file: https://github.com/rajentrivedi/tokenizer-x/commit/8ca56bd91925c44894bd4ca75048855c5a1eefa9#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34L18

This prevents installing the package as a sub-dependency in packages for Laravel 11, because the default `minimum-stability` is `stable`.

```
- PACKAGE requires rajentrivedi/tokenizer-x dev-upgrade-laravel-11 -> found rajentrivedi/tokenizer-x[dev-upgrade-laravel-11] but it does not match your minimum-stability.
```

### How to reproduce the bug

/

### Package Version

dev-upgrade-laravel-11

### PHP Version

8.3

### Laravel Version

11.0

### Which operating systems does with happen with?

macOS

**Comment by rajentrivedi** [comment]
Yes, Planning to publish stable, but I am too busy with my Job, it will be really nice if you can contribute.

Thank You.

**Comment by mechelon** [comment]
#26   
It's not much, but I think that's everything needed for a stable release. Hope that helps! 😊

**Comment by mechelon** [comment]
Could you add a (for example) 1.1.0 tag + release as well so it's available on packagist? :)
