### ISSUE TITLE
[Bug]: Can't install on Laravel 11

### ISSUE THREAD

**Issue by FernandoAcTr** [rajentrivedi/tokenizer-x#29]
### What happened?

Runing `composer require rajentrivedi/tokenizer-x` throws the next error: 

```
- rajentrivedi/tokenizer-x[1.0.0, ..., 1.0.2] require illuminate/contracts ^10.0 -> found illuminate/contracts[v10.0.0, ..., v10.48.16] but these were not loaded, likely 
because it conflicts with another require.
    - Root composer.json requires rajentrivedi/tokenizer-x * -> satisfiable by rajentrivedi/tokenizer-x[1.0.0, 1.0.1, 1.0.2].
```

### How to reproduce the bug

Run ```composer require rajentrivedi/tokenizer-x ``` in Laravel 11 project

### Package Version

1.0.2

### PHP Version

8.2.0

### Laravel Version

11.9

### Which operating systems does with happen with?

Windows

**Comment by scotteuser** [comment]
I think it just needs a release to packagist because dependencies on `main`seem to work fine.

**Comment by rajentrivedi** [comment]
new release is created, its working fine.

@FernandoAcTr thank you for reporting & please try again and confirm, so I can close the issue

**Comment by FernandoAcTr** [comment]
@rajentrivedi Yes!, it's working know. Thanks.

**Comment by rajentrivedi** [comment]
closing this issue as its working.
