### ISSUE TITLE
does it support cl100k_base for gpt-4?

### ISSUE THREAD

**Issue by boynet** [rajentrivedi/tokenizer-x#6]
### What happened?

tanks a lot for you work, I wonder is it support cl100k_base for gpt-4?

### How to reproduce the bug

tried to look at the code couldn't understand it

### Package Version

2

### PHP Version

8

### Laravel Version

9

### Which operating systems does with happen with?

Windows

**Comment by rajentrivedi** [comment]
Thanx for reporting the issue.

**Comment by rajentrivedi** [comment]
I would like to add this, but currently I don't have GPT-4 access to test this.

**Comment by rajentrivedi** [comment]
Currently we are not supporting cl100k_base for gpt-4.
